### PR TITLE
Adding eMMC Support

### PR DESCRIPTION
**Pull request by thebitstick**
Fixes Issue #16 for eMMC Support.

### CODE REVIEW

**Comment by lucasvr** [comment]
Thanks a bunch!

**Comment by fyrak1s** [comment]
Sadly this gives me a regression when installing via qemu on to a partition `/dev/vda1`, the installer fails to start with:

```
No valid partitions found
Create one using "gparted" or "cfdisk"
```
When I revert the changes it works as normal.
I have not tested on a real system but I suppose it would fail as well!

@lucasvr would you mind taking a look?

**Comment by fyrak1s** [comment]
It seems we need to append the `partitionList` variable rather then overwrite it, like this:
```diff
		p = re.compile(r'\b[a-z]+[0-9]+\b')
		pmmcblk = re.compile(r'\b[a-z]+[a-z]+[a-z]+[a-z]+[a-z]+[a-z]+[0-9]+[a-z]+[0-9]+\b')
		pnvme = re.compile(r'\b[a-z]+[0-9]+[a-z]+[0-9]+p[0-9]+\b')
		partitionsList = [x for x in devicesList if p.match(x) and not 'loop' in x]
-		partitionsList = [x for x in devicesList if pmmcblk.match(x) and not 'loop' in x]
+		partitionsList += [x for x in devicesList if pmmcblk.match(x) and not 'loop' in x]
		partitionsList += [x for x in devicesList if pnvme.match(x) and not 'loop' in x]
		partitionsList.sort()

		d = re.compile(r'\b[a-z]+\b')
		dmmcblk = re.compile(r'\b[a-z]+[a-z]+[a-z]+[a-z]+[a-z]+[a-z]+[0-9]+\b')
		dnvme = re.compile(r'\b[a-z]+[0-9]+[a-z]+[0-9]+\b')
		discsList = [x for x in devicesList if d.match(x) and not 'loop' in x]
-		discsList = [x for x in devicesList if dmmcblk.match(x) and not 'loop' in x]
+		discsList += [x for x in devicesList if dmmcblk.match(x) and not 'loop' in x]
		discsList += [x for x in devicesList if dnvme.match(x) and not 'loop' in x]
		discsList.sort()
```

That fixed it at least for me, so I committed it in 4899c58b03e7f52998f19b2aa20abc58284e10be.

**Comment by hishamhm** [comment]
@Nuc1eoN that change looks sensible! :+1:

**Comment by fyrak1s** [comment]
@hishamhm Awesome thanks a lot for double checking! 👍

**Pull request merged**
